[package]
name = "Run"
version = "0.0.1"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/VHSgunzo/Run-wrapper"
description = "ELF wrapper for RunImage Run.sh script in the extracted form"

[profile.release]
strip = "symbols"

[dependencies]
exec = "*"
which = "*"
chrono = "*"
